
import React from 'react';
import Feature from '../../components/feature/Feature';
import './whatGPT3.css';

const WhatGPT3 = () => (
  <div className="gpt3__whatgpt3 section__margin" id="wgpt3">
    <div className="gpt3__whatgpt3-feature">
      <Feature title="What is Codely" text="Codely is an intuitive app designed to help you master coding interviews with ease. It offers a curated selection of over 100 practice questions, covering both theoretical concepts and practical scenarios across 5 popular programming languages: C, Java, JavaScript, C++, and SQL. Whether you're a beginner or an experienced developer, Codely provides a focused environment to sharpen your problem-solving skills and deepen your understanding of key topics." />
    </div>
    <div className="gpt3__whatgpt3-heading">
      <h1 className="gradient__text">The possibilities are beyond your imagination</h1>
    </div>
    <div className="gpt3__whatgpt3-container">
      <Feature title="AI Generated Levels" text="Random tests generated by our AI that will help you practice what you learn." />
      <Feature title="Over 100 Levels" text="Over 100 Levels that you can choose from , with 5 different programming languages and more to come" />
      <Feature title="Every programming language" text="From C , to Python or Javascript , every language is sure to be available in the future in Codely" />
    </div>
  </div>
);

export default WhatGPT3;
